project:
  type: website
  output-dir: docs

website:
  title: "Filippo Romiti"
  description: "Personal Website for notes and projects"
  navbar:
    title: false
    left:
      - text: "Filippo Romiti"
        href: "/"
      - text: "Scuola"
        href: school
      - text: "Uni"
        href: uni
      - text: "Notebook"
        href: posts
  site-path: "/"
  page-footer:
    center:
      - text: "About"
        href: about
      - text: "License"
        href: license


format:
  html:
    theme: /home/rmtfpp/Templates/default.scss
    toc: true



